# Generated by Django 5.1.1 on 2024-10-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_game_description_game_genre_game_platforms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
