# Generated by Django 5.1.1 on 2024-10-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_game_cover_url_alter_game_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
