# Generated by Django 5.1.1 on 2024-10-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_game_cover_url_alter_game_genre_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-rating', 'name'], name='members_gam_rating_79360c_idx'),
        ),
    ]
