# Generated by Django 5.1.1 on 2024-10-18 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_game_members_gam_rating_79360c_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='game',
            name='members_gam_rating_79360c_idx',
        ),
    ]
