# Generated by Django 5.1.1 on 2024-10-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_game_members_gam_rating_79360c_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(unique=True)),
                ('name', models.TextField()),
                ('cover_url', models.TextField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('platforms', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
