# Generated by Django 5.1.1 on 2024-10-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_gamestest'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='age_ratings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='companies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='screenshots',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
