# Generated by Django 5.1.1 on 2024-10-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_screenshot_delete_gamestest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='companies',
        ),
        migrations.AddField(
            model_name='game',
            name='companies',
            field=models.ManyToManyField(blank=True, to='members.company'),
        ),
    ]
